<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-105EU33" failures="1" tests="1" name="qa.runners.tc4Runner" time="9.693" errors="0" timestamp="2025-05-19T11:47:20 MST" skipped="0">
  <testcase classname="qa.runners.tc4Runner" name="runScenario" time="9.693">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at qa.stepDefinitions.tc4StepDefinition.validate_on_home_page(tc4StepDefinition.java:46)
at âœ½.validate "CHANDLER VACATION RENTALS" on home page(file:///C:/Users/mengj/Documents/QA_Projects/OneOak/src/test/resources/featureFiles/TestCase4.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- qa.runners.tc4Runner -->
